# Generated by Django 4.1.7 on 2023-04-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_user',
        ),
    ]
