# Generated by Django 4.1.7 on 2023-04-13 10:39

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_remove_userprofile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to=userProfile.models.user_director_path),
        ),
    ]
