# Generated by Django 4.1.7 on 2023-04-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_comment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
