# Generated by Django 4.1.7 on 2023-04-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_id_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id_comment',
        ),
    ]
